export const DEFAULT_PAGE_SIZE = 25;

export const COMPONENT_STATUS = {
  PENDING: "PENDING",
  CREATING: "CREATING",
  CREATED: "CREATED",
  DELETING: "DELETING",
  EDITING: "EDITING",
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};
