export const DEFAULT_PAGE_SIZE = 25;

export const INPUT_MODE = {
  INPUT_TEXT: "INPUT_TEXT",
  AUTOCOMPLETE: "AUTOCOMPLETE",
};

export const DEFAULT_FILTER_PG_INDEX = 0;
export const SELECTOR_REQUIRED = "required";
export const SELECTOR_OPTIONAL = "optional";
export const SELECTOR_DEFAULT = "all";
export const DEFAULT_FILTER = "default";

export const COMPONENT_STATUS = {
  PENDING: "PENDING",
  CREATING: "CREATING",
  CREATED: "CREATED",
  DELETING: "DELETING",
  EDITING: "EDITING",
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",

  INIT: "INIT",
  AUTHORIZED_FAILED: "AUTHORIZED_FAILED",
  AUTHORIZED_SUCCESS: "AUTHORIZED_SUCCESS",

  CONFIGURING: "CONFIGURING",

  CONFIG_DEVICE: {
    HAS_NEW_FW: "HAS_NEW_FW",
    CONFIGURING: "CONFIGURING",
    CONFIG_FAILED: "CONFIG_FAILED",
    CONFIG_SUCCESS: "CONFIG_SUCCESS",
  },

  UPGRADE_OTA: {
    GETTING_INFO: "GETTING_INFO",
  },

  SHOW_DETAIL: "SHOW_DETAIL",

  DEVICE: {
    CHANGE_STATUS: "CHANGE_STATUS",
    DOWNLOAD_CERT: "DOWNLOAD_CERT",
  },

  FIRMWARE: {
    DOWNLOAD: "DOWNLOAD",
    UPLOAD: "UPLOAD",
    ATTACH: "ATTACH",
  },

  APP: {
    ATTACH_TYPE: "ATTACH_TYPE",
    SHOW_APP_SCOPE: "SHOW_APP_SCOPE",
    BUILD_APP: "BUILD_APP",
    SELECT_EMAIL: "SELECT_EMAIL",
    SECRET: "SECRET",
    MANAGE_ENTITY: "MANAGE_ENTITY",
    EDIT_NAME: "EDIT_NAME",
    MORE_SETTING: "MORE_SETTING",
    APP_NOTIFICATION: "APP_NOTIFICATION",
    DELETING_NOTIF: "DELETING_NOTIF",
    DELETING_NOTIF_SUCCESS: "DELETING_NOTIF_SUCCESS",
  },
};

export const DEVICE_TYPES = {
  SWITCH: "SWITCH",
  LIGHT: "LIGHT",
  SHUTTER: "SHUTTER",
  AC_UNIT: "AC_UNIT",
  FAN: "FAN",
  SENSOR: "SENSOR",
  WATER_PURIFIER: "WATERPURIFIER",
  SMART_ELECTRIC_METER: "SMARTELECTRICMETER",
};

export const VISIBILITY_TABLE_KEYS = {
  OLD_PASS: "isShowingOldPass",
  NEW_PASS: "isShowingNewPass",
  CONFIRM_PASS: "isShowingConfirmPass",
};
